[package]
name = "server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "splander_server"
path = "server/main.rs"

[build]
target-dir = "build/"

[dependencies]
tokio = { version = "1", features = ["full"] }
